// GENERATED by scripts/gen_constants.py from astropy 6.0.1.
// Do not edit by hand. Single source of truth for FUNDAMENTAL constants (CGS).
// Composite constants (sigma_sb, sigma_T) are derived in `crate::derived`.

/// astropy.constants.G [cm^3 g^-1 s^-2]
pub const G: f64 = 6.674299999999999e-08;

/// astropy.constants.c [cm s^-1]
pub const C_LIGHT: f64 = 29979245800.0;

/// astropy.constants.M_sun [g]
pub const M_SUN: f64 = 1.988409870698051e+33;

/// astropy.constants.m_p [g]
pub const M_P: f64 = 1.67262192369e-24;

/// astropy.constants.m_e [g]
pub const M_E: f64 = 9.1093837015e-28;

/// astropy.constants.h [erg s]
pub const H_PLANCK: f64 = 6.62607015e-27;

/// astropy.constants.k_B [erg K^-1]
pub const K_BOLTZMANN: f64 = 1.380649e-16;

/// astropy.constants.alpha [dimensionless]
pub const ALPHA: f64 = 0.0072973525693;

/// Nanometres to centimetres [cm nm^-1] (exact: 1 nm = 1e-7 cm).
pub const NM_TO_CM: f64 = 1e-7;
