//! # accretion-core
//!
//! Pure-Rust accretion-disk physics for the `accretion` game. Zero Godot
//! dependency; `cargo test`-able in isolation. Ported from
//! `BlackHoleResearch/blackhole/physics/accretion.py`.
//!
//! Fundamental physical constants live in [`constants`] (generated from astropy
//! by `scripts/gen_constants.py`). Composite constants (`SIGMA_SB`, `SIGMA_T`)
//! are derived from those fundamentals in [`derived`]. Golden expected values
//! live in `tests/fixtures/golden.json` (generated by `scripts/gen_golden.py`).

pub mod constants;
pub mod derived;

use constants::{C_LIGHT, G, H_PLANCK, K_BOLTZMANN, M_P, M_SUN, NM_TO_CM};
use derived::{SIGMA_SB, SIGMA_T};

/// Eddington luminosity `L_Edd` \[erg/s\] for a black hole of mass `m_bh_msun`.
///
/// `L_Edd = 4 pi G M m_p c / sigma_T`.
///
/// # Reference
/// Eddington 1926; Frank, King & Raine 2002, Eq. (1.5).
pub fn l_eddington(m_bh_msun: f64) -> f64 {
    let m_g = m_bh_msun * M_SUN;
    4.0 * std::f64::consts::PI * G * m_g * M_P * C_LIGHT / SIGMA_T
}

/// Bolometric luminosity \[erg/s\] from accretion rate `mdot_gs` \[g/s\] at
/// radiative efficiency `eta`: `L = eta Mdot c^2`.
///
/// # Reference
/// Novikov & Thorne 1973.
pub fn luminosity_from_mdot(mdot_gs: f64, eta: f64) -> f64 {
    eta * mdot_gs * C_LIGHT * C_LIGHT
}

/// Eddington ratio `lambda = L / L_Edd` (dimensionless).
pub fn eddington_ratio(m_bh_msun: f64, mdot_gs: f64, eta: f64) -> f64 {
    luminosity_from_mdot(mdot_gs, eta) / l_eddington(m_bh_msun)
}

/// Accretion rate \[g/s\] from bolometric luminosity \[erg/s\] at efficiency `eta`.
///
/// # Reference
/// Novikov & Thorne 1973.
pub fn mdot_from_luminosity(l: f64, eta: f64) -> f64 {
    l / (eta * C_LIGHT * C_LIGHT)
}

// ---------------------------------------------------------------------------
// Time evolution / gameplay dynamics
// ---------------------------------------------------------------------------

/// Advance the black-hole mass \[M_sun\] by `dt_s` \[s\] while accreting at
/// `mdot_gs` \[g/s\] with radiative efficiency `eta`.
///
/// Mass grows by the rest mass that crosses the horizon, `dM/dt = (1 - eta) Mdot`;
/// the radiated fraction `eta` does not add to the hole. For a constant feed rate
/// over the step this is exact (the right-hand side is constant in `Mdot`).
///
/// # Reference
/// Frank, King & Raine 2002, *Accretion Power in Astrophysics*, Ch. 1.
pub fn advance_mass(m_bh_msun: f64, mdot_gs: f64, eta: f64, dt_s: f64) -> f64 {
    let m_g = m_bh_msun * M_SUN + (1.0 - eta) * mdot_gs * dt_s;
    m_g / M_SUN
}

/// Salpeter (Eddington) e-folding time \[s\]: the timescale on which mass grows by
/// a factor `e` when accreting at the Eddington limit with efficiency `eta`.
///
/// `t_S = (eta / (1 - eta)) * sigma_T * c / (4 pi G m_p)`. Mass-independent,
/// because both the Eddington rate and the mass scale linearly with `M`.
///
/// # Reference
/// Salpeter 1964, ApJ 140, 796.
pub fn salpeter_time_s(eta: f64) -> f64 {
    (eta / (1.0 - eta)) * SIGMA_T * C_LIGHT / (4.0 * std::f64::consts::PI * G * M_P)
}

/// Net disk-support fraction as a function of Eddington ratio `lambda = L / L_Edd`.
///
/// Returns `1 - lambda`, the radiation-pressure-modified effective gravity
/// `g_eff / g`: positive (net inward, the disk is bound and recovers) for
/// `lambda < 1`, zero at the Eddington limit, and negative (net outward, the
/// disk is unbound and disrupts) for `lambda > 1`. It is dimensionless; the
/// presentation layer multiplies it by a gameplay timescale to evolve a
/// disk-integrity meter (rule 02 keeps that tuning constant out of the physics).
///
/// # Reference
/// Eddington 1926: radiation pressure subtracts from gravity as `g(1 - L/L_Edd)`.
pub fn integrity_rate(eddington_ratio: f64) -> f64 {
    1.0 - eddington_ratio
}

/// Shakura-Sunyaev disk temperature \[K\] at radius `r_cm` \[cm\].
///
/// Bare form: `T = (3 G M Mdot / (8 pi sigma_sb r^3))^(1/4)`. Omits the inner-
/// boundary factor `(1 - sqrt(r_in/r))^(1/4)` — see rule 02.
///
/// # Reference
/// Shakura & Sunyaev 1973, A&A 24, 337.
pub fn disk_temperature(r_cm: f64, m_bh_msun: f64, mdot_gs: f64) -> f64 {
    let m_g = m_bh_msun * M_SUN;
    let t4 = 3.0 * G * m_g * mdot_gs / (8.0 * std::f64::consts::PI * SIGMA_SB * r_cm * r_cm * r_cm);
    t4.powf(0.25)
}

/// Gravitational radius `R_g = GM/c^2` \[cm\].
pub fn gravitational_radius_cm(m_bh_msun: f64) -> f64 {
    G * (m_bh_msun * M_SUN) / (C_LIGHT * C_LIGHT)
}

/// Schwarzschild radius `r_s = 2 GM/c^2` \[cm\].
pub fn r_s(m_bh_msun: f64) -> f64 {
    2.0 * gravitational_radius_cm(m_bh_msun)
}

/// ISCO radius in units of `R_g = GM/c^2` (dimensionless spin parameter).
///
/// # Reference
/// Bardeen, Press & Teukolsky 1972, ApJ 178, 347, Eq. (2.21).
pub fn isco_radius(spin: f64) -> f64 {
    let a = spin;
    let z1 = 1.0 + (1.0 - a * a).cbrt() * ((1.0 + a).cbrt() + (1.0 - a).cbrt());
    let z2 = (3.0 * a * a + z1 * z1).sqrt();
    3.0 + z2 - ((3.0 - z1) * (3.0 + z1 + 2.0 * z2)).sqrt()
}

/// ISCO radius \[cm\] for mass `m_bh_msun` and spin `spin`.
pub fn r_isco(m_bh_msun: f64, spin: f64) -> f64 {
    isco_radius(spin) * gravitational_radius_cm(m_bh_msun)
}

/// Specific energy `E/(mu c^2)` (dimensionless) of the prograde ISCO circular
/// orbit at spin `spin`, i.e. the fraction of rest-mass energy a unit mass still
/// carries at the inner edge.
///
/// `E = (r^(3/2) - 2 r^(1/2) + a) / (r^(3/4) (r^(3/2) - 3 r^(1/2) + 2 a)^(1/2))`
/// with `r = r_isco` in gravitational radii and `a = spin` (upper/prograde sign).
///
/// # Reference
/// Bardeen, Press & Teukolsky 1972, ApJ 178, 347, Eq. (2.12)-(2.13).
pub fn isco_specific_energy(spin: f64) -> f64 {
    let a = spin;
    let r = isco_radius(spin);
    let sqrt_r = r.sqrt();
    let r32 = r * sqrt_r;
    let r34 = r32.sqrt();
    let numerator = r32 - 2.0 * sqrt_r + a;
    let denominator = r34 * (r32 - 3.0 * sqrt_r + 2.0 * a).sqrt();
    numerator / denominator
}

/// Radiative efficiency `eta = 1 - E_isco` of a thin disk around a Kerr black
/// hole of dimensionless spin `spin`.
///
/// Ranges from ~0.057 (Schwarzschild, `a = 0`) to ~0.32 at the Thorne spin limit
/// `a = 0.998`, and up to `1 - 1/sqrt(3) ~= 0.42` as `a -> 1`. Spinning up the
/// hole therefore raises both the energy yield per gram and the proximity to the
/// Eddington edge.
///
/// # Reference
/// Novikov & Thorne 1973; Thorne 1974, ApJ 191, 507 (spin limit).
pub fn efficiency_from_spin(spin: f64) -> f64 {
    1.0 - isco_specific_energy(spin)
}

/// Coordinate orbital frequency \[Hz\] of a prograde circular equatorial orbit at
/// radius `r_over_rg` (in gravitational radii `R_g = GM/c^2`) around a Kerr black
/// hole of mass `m_bh_msun` and dimensionless spin `spin`.
///
/// `Omega = c^3 / (G M) * 1 / (r^(3/2) + a)`; `f = Omega / (2 pi)`. At the ISCO
/// this is the upper bound of the orbital (and a candidate high-frequency QPO)
/// signal, scaling as `1 / M`.
///
/// # Reference
/// Bardeen, Press & Teukolsky 1972, ApJ 178, 347, Eq. (2.16).
pub fn orbital_frequency_hz(m_bh_msun: f64, r_over_rg: f64, spin: f64) -> f64 {
    let omega = C_LIGHT.powi(3) / (G * m_bh_msun * M_SUN) / (r_over_rg.powf(1.5) + spin);
    omega / (2.0 * std::f64::consts::PI)
}

/// Linear sRGB blackbody color at temperature `temp_k` \[K\], brightest channel
/// normalized to 1.0 (HDR-friendly chromaticity).
///
/// # References
/// Planck 1901; CIE 1931; Wyman, Sloan & Shirley 2013; IEC 61966-2-1.
pub fn blackbody_rgb(temp_k: f64) -> (f64, f64, f64) {
    if temp_k <= 0.0 || !temp_k.is_finite() {
        return (0.0, 0.0, 0.0);
    }

    let (mut x, mut y, mut z) = (0.0_f64, 0.0_f64, 0.0_f64);
    let (lambda_min_nm, lambda_max_nm, step_nm) = (380.0, 780.0, 5.0);
    let mut lambda_nm = lambda_min_nm;
    while lambda_nm <= lambda_max_nm {
        let b = planck_spectral_radiance(lambda_nm * NM_TO_CM, temp_k);
        let (xb, yb, zb) = cie_xyz_cmf(lambda_nm);
        x += b * xb;
        y += b * yb;
        z += b * zb;
        lambda_nm += step_nm;
    }

    let sum = x + y + z;
    if sum <= 0.0 {
        return (0.0, 0.0, 0.0);
    }
    let (x, y, z) = (x / sum, y / sum, z / sum);

    let r = 3.240_625 * x - 1.537_208 * y - 0.498_629 * z;
    let g = -0.968_931 * x + 1.875_756 * y + 0.041_518 * z;
    let b = 0.055_710 * x - 0.204_021 * y + 1.056_996 * z;

    let r = r.max(0.0);
    let g = g.max(0.0);
    let b = b.max(0.0);

    let peak = r.max(g).max(b);
    if peak <= 0.0 {
        return (0.0, 0.0, 0.0);
    }
    (r / peak, g / peak, b / peak)
}

fn planck_spectral_radiance(lambda_cm: f64, temp_k: f64) -> f64 {
    let numerator = 2.0 * H_PLANCK * C_LIGHT * C_LIGHT / lambda_cm.powi(5);
    let exponent = H_PLANCK * C_LIGHT / (lambda_cm * K_BOLTZMANN * temp_k);
    numerator / (exponent.exp() - 1.0)
}

fn cie_xyz_cmf(lambda_nm: f64) -> (f64, f64, f64) {
    fn g(lambda: f64, mean: f64, sigma_lo: f64, sigma_hi: f64) -> f64 {
        let sigma = if lambda < mean { sigma_lo } else { sigma_hi };
        let t = (lambda - mean) / sigma;
        (-0.5 * t * t).exp()
    }

    let x = 1.056 * g(lambda_nm, 599.8, 37.9, 31.0) + 0.362 * g(lambda_nm, 442.0, 16.0, 26.7)
        - 0.065 * g(lambda_nm, 501.1, 20.4, 26.2);
    let y = 0.821 * g(lambda_nm, 568.8, 46.9, 40.5) + 0.286 * g(lambda_nm, 530.9, 16.3, 31.1);
    let z = 1.217 * g(lambda_nm, 437.0, 11.8, 36.0) + 0.681 * g(lambda_nm, 459.0, 26.0, 13.8);
    (x, y, z)
}
