//! # accretion-core
//!
//! Pure-Rust accretion-disk physics for the `accretion` game. Zero Godot
//! dependency; `cargo test`-able in isolation.
//!
//! ## Module map
//!
//! | Module | Responsibility |
//! |---|---|
//! | [`constants`] | Fundamental CGS constants (generated from astropy) |
//! | [`derived`] | Composite constants (`sigma_sb`, `sigma_T`) from fundamentals |
//! | [`eddington`] | Eddington luminosity, `lambda`, accretion–luminosity relations |
//! | [`kerr`] | Kerr radii, ISCO, efficiency, angular momentum, orbital frequency |
//! | [`disk`] | Shakura–Sunyaev disk temperature (bare SS73 form) |
//! | [`evolution`] | Mass and spin evolution under accretion; integrity driver |
//! | [`colorimetry`] | Planck → CIE → sRGB blackbody colour |
//!
//! Golden expected values live in `tests/fixtures/golden.json` (generated by
//! `scripts/gen_golden.py`). Every public formula cites its primary source in
//! the module or function documentation.
//!
//! ## Re-exports
//!
//! All game and test code may use the crate root (`accretion_core::l_eddington`,
//! etc.) without knowing the internal module layout.

pub mod colorimetry;
pub mod constants;
pub mod derived;
pub mod disk;
pub mod eddington;
pub mod evolution;
pub mod kerr;

// --- Eddington -------------------------------------------------------------

pub use eddington::{
    eddington_ratio, l_eddington, luminosity_from_mdot, mdot_at_eddington, mdot_from_luminosity,
};

// --- Kerr geometry ---------------------------------------------------------

pub use kerr::{
    THORNE_SPIN_LIMIT, efficiency_from_spin, gravitational_radius_cm, isco_radius,
    isco_specific_angular_momentum, isco_specific_energy, orbital_frequency_hz, r_isco, r_s,
    specific_angular_momentum,
};

// --- Disk ------------------------------------------------------------------

pub use disk::disk_temperature;

// --- Evolution -------------------------------------------------------------

pub use evolution::{advance_mass, advance_spin, integrity_rate, salpeter_time_s};

// --- Colorimetry -----------------------------------------------------------

pub use colorimetry::blackbody_rgb;

// --- Derived constants (re-export for golden tests) ------------------------

pub use derived::{H_BAR, SIGMA_SB, SIGMA_T};
