#!/usr/bin/env python3
"""Generate crates/accretion-core/src/constants.rs from astropy (CGS).

Single source of truth. Re-run to update; commit the diff. Do not hand-edit the output.
"""
from __future__ import annotations

import astropy
import astropy.constants as c

vals = {
    "G": (float(c.G.cgs.value), "cm^3 g^-1 s^-2", "astropy.constants.G"),
    "C_LIGHT": (float(c.c.cgs.value), "cm s^-1", "astropy.constants.c"),
    "M_SUN": (float(c.M_sun.cgs.value), "g", "astropy.constants.M_sun"),
    "M_P": (float(c.m_p.cgs.value), "g", "astropy.constants.m_p"),
    "SIGMA_T": (float(c.sigma_T.cgs.value), "cm^2", "astropy.constants.sigma_T"),
    "SIGMA_SB": (float(c.sigma_sb.cgs.value), "erg cm^-2 s^-1 K^-4", "astropy.constants.sigma_sb"),
    "H_PLANCK": (float(c.h.cgs.value), "erg s", "astropy.constants.h"),
    "K_BOLTZMANN": (float(c.k_B.cgs.value), "erg K^-1", "astropy.constants.k_B"),
}

out = [
    f"// GENERATED by scripts/gen_constants.py from astropy {astropy.__version__}.\n",
    "// Do not edit by hand. Single source of truth for physical constants (CGS).\n\n",
]
for name, (val, unit, src) in vals.items():
    out.append(f"/// {src} [{unit}]\n")
    out.append(f"pub const {name}: f64 = {val!r};\n\n")

# Exact unit conversion (not an astropy constant; definitionally exact).
out.append("/// Nanometres to centimetres [cm nm^-1] (exact: 1 nm = 1e-7 cm).\n")
out.append("pub const NM_TO_CM: f64 = 1e-7;\n\n")

open("crates/accretion-core/src/constants.rs", "w").write("".join(out))
print("wrote constants.rs from astropy", astropy.__version__)
