#!/usr/bin/env python3
"""Generate crates/accretion-core/src/constants.rs from astropy (CGS).

Single source of truth for the FUNDAMENTAL constants. Composite constants
(Stefan-Boltzmann sigma_sb, Thomson cross-section sigma_T) are NOT emitted here;
they are derived from these fundamentals in `accretion-core::derived`, where the
mathematical relation is exact and explicit. Re-run to update; commit the diff.
Do not hand-edit the output.
"""
from __future__ import annotations

import astropy
import astropy.constants as c

# Only FUNDAMENTAL constants. Anything that is an exact mathematical function of
# these (sigma_sb, sigma_T) is derived in Rust, not tabulated here.
vals = {
    "G": (float(c.G.cgs.value), "cm^3 g^-1 s^-2", "astropy.constants.G"),
    "C_LIGHT": (float(c.c.cgs.value), "cm s^-1", "astropy.constants.c"),
    "M_SUN": (float(c.M_sun.cgs.value), "g", "astropy.constants.M_sun"),
    "M_P": (float(c.m_p.cgs.value), "g", "astropy.constants.m_p"),
    "M_E": (float(c.m_e.cgs.value), "g", "astropy.constants.m_e"),
    "H_PLANCK": (float(c.h.cgs.value), "erg s", "astropy.constants.h"),
    "K_BOLTZMANN": (float(c.k_B.cgs.value), "erg K^-1", "astropy.constants.k_B"),
    "ALPHA": (float(c.alpha.value), "dimensionless", "astropy.constants.alpha"),
}

out = [
    f"// GENERATED by scripts/gen_constants.py from astropy {astropy.__version__}.\n",
    "// Do not edit by hand. Single source of truth for FUNDAMENTAL constants (CGS).\n",
    "// Composite constants (sigma_sb, sigma_T) are derived in `crate::derived`.\n\n",
]
for name, (val, unit, src) in vals.items():
    out.append(f"/// {src} [{unit}]\n")
    out.append(f"pub const {name}: f64 = {val!r};\n\n")

# Exact unit conversion (not an astropy constant; definitionally exact).
out.append("/// Nanometres to centimetres [cm nm^-1] (exact: 1 nm = 1e-7 cm).\n")
out.append("pub const NM_TO_CM: f64 = 1e-7;\n\n")

# Single trailing newline (rustfmt-clean), internal spacing preserved.
text = "".join(out).rstrip() + "\n"
open("crates/accretion-core/src/constants.rs", "w").write(text)
print("wrote constants.rs from astropy", astropy.__version__)
